### ISSUE TITLE
Unable to load library 'libmediainfo': JNA native support (win32-amd64/libmediainfo.dll)

### ISSUE THREAD

**Issue by frankred** [caprica/vlcj-info#3]
I just bounded the MediaInfo natives this way:

``` java
System.setProperty("jna.library.path", "C:\\Program Files\\MediaInfo");
MediaInfo info = MediaInfo.mediaInfo("D:/media/musik.mp3");
info.dump(new OutputStreamWriter(System.out));
```

I get the following error:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'libmediainfo': JNA native support (win32-amd64/libmediainfo.dll) not found in resource path (C:\Program Files\Java\jdk1.8.0_45\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_45\jre\lib\ext\zipfs.jar;D:\workspace-javafx\jSona-maven\target\classes;C:\Users\Frank\.m2\repository\uk\co\caprica\vlcj\3.1.0\vlcj-3.1.0.jar;C:\Users\Frank\.m2\repository\net\java\dev\jna\jna\3.5.2\jna-3.5.2.jar;C:\Users\Frank\.m2\repository\net\java\dev\jna\platform\3.5.2\platform-3.5.2.jar;C:\Users\Frank\.m2\repository\org\apache\lucene\lucene-core\4.10.3\lucene-core-4.10.3.jar;C:\Users\Frank\.m2\repository\org\apache\lucene\lucene-analyzers-common\4.10.3\lucene-analyzers-common-4.10.3.jar;C:\Users\Frank\.m2\repository\org\apache\lucene\lucene-queryparser\4.10.3\lucene-queryparser-4.10.3.jar;C:\Users\Frank\.m2\repository\org\apache\lucene\lucene-queries\4.10.3\lucene-queries-4.10.3.jar;C:\Users\Frank\.m2\repository\org\apache\lucene\lucene-sandbox\4.10.3\lucene-sandbox-4.10.3.jar;C:\Users\Frank\.m2\repository\com\google\code\gson\gson\2.3.1\gson-2.3.1.jar;C:\Users\Frank\.m2\repository\com\github\tulskiy\jkeymaster\1.2-SNAPSHOT\jkeymaster-1.2-20140816.071050-1.jar;C:\Users\Frank\.m2\repository\net\sf\javamusictag\jid3lib\0.5.4\jid3lib-0.5.4.jar;C:\Users\Frank\.m2\repository\uk\co\caprica\vlcj-info\1.0.0\vlcj-info-1.0.0.jar;C:\Users\Frank\.m2\repository\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar;C:\Users\Frank\.m2\repository\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\Frank\.m2\repository\commons-httpclient\commons-httpclient\3.1\commons-httpclient-3.1.jar;C:\Users\Frank\.m2\repository\commons-logging\commons-logging\1.0.4\commons-logging-1.0.4.jar;C:\Users\Frank\.m2\repository\commons-codec\commons-codec\1.2\commons-codec-1.2.jar;C:\Users\Frank\.m2\repository\org\jsoup\jsoup\1.8.1\jsoup-1.8.1.jar;C:\Users\Frank\.m2\repository\junit\junit\4.12\junit-4.12.jar;C:\Users\Frank\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\Frank\.m2\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;C:\Users\Frank\.m2\repository\org\codehaus\jettison\jettison\1.3.7\jettison-1.3.7.jar;C:\Users\Frank\.m2\repository\stax\stax-api\1.0.1\stax-api-1.0.1.jar;C:\Users\Frank\.m2\repository\com\github\axet\vget\1.1.23\vget-1.1.23.jar;C:\Users\Frank\.m2\repository\org\apache\httpcomponents\httpclient\4.1.3\httpclient-4.1.3.jar;C:\Users\Frank\.m2\repository\org\apache\httpcomponents\httpcore\4.1.4\httpcore-4.1.4.jar;C:\Users\Frank\.m2\repository\com\github\axet\wget\1.2.11\wget-1.2.11.jar;C:\Users\Frank\.m2\repository\com\thoughtworks\xstream\xstream\1.4.2\xstream-1.4.2.jar;C:\Users\Frank\.m2\repository\xmlpull\xmlpull\1.1.3.1\xmlpull-1.1.3.1.jar;C:\Users\Frank\.m2\repository\xpp3\xpp3_min\1.1.4c\xpp3_min-1.1.4c.jar;C:\Users\Frank\.m2\repository\com\github\axet\threads\0.0.2\threads-0.0.2.jar;C:\Users\Frank\.m2\repository\org\controlsfx\controlsfx\8.20.8\controlsfx-8.20.8.jar;C:\Users\Frank\.m2\repository\org\controlsfx\openjfx-dialogs\1.0.2\openjfx-dialogs-1.0.2.jar;D:\Program Files (x86)\JetBrains\IntelliJ IDEA 14.0.2\lib\idea_rt.jar)
    at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:220)
    at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:322)
    at com.sun.jna.Library$Handler.<init>(Library.java:142)
    at com.sun.jna.Native.loadLibrary(Native.java:387)
    at com.sun.jna.Native.loadLibrary(Native.java:366)
    at uk.co.caprica.vlcjinfo.binding.LibMediaInfo.<clinit>(LibMediaInfo.java:33)
    at uk.co.caprica.vlcjinfo.MediaInfo.mediaInfo(MediaInfo.java:52)
    at de.roth.jsona.Sandbox.main(Sandbox.java:18)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

Is there a smooth way to bin my native dependecies in my maven project ?

**Comment by caprica** [comment]
I'm not sure, this project assumes you have the MediaInfo package already installed.

**Comment by frankred** [comment]
Yeah I have it already installed in my "C:\Program Files\MediaInfo" folder. But where is the `libmediainfo.dll` I only got a `MediaInfo.dll` in my directory installed.

**Comment by caprica** [comment]
I don't recall personally using this project on Windows, there may be an incorrect assumption in the "LibMediaInfo.java" class, i.e.:

LibMediaInfo INSTANCE = (LibMediaInfo) Native.loadLibrary(Platform.isWindows() ? "libmediainfo" : "mediainfo", LibMediaInfo.class);

If you can get the source for this project, try changing that so the Windows clause is "MediaInfo" rather than libmediainfo.

If that works, I'll make the change and a new release soon.

**Comment by frankred** [comment]
Ok thanks! I'm not very fimilar with maven2 but I will try my best ;)

**Comment by frankred** [comment]
Hi again,

I just tested a lot of names for the lib but nothing seemed to work. I just quit using vlcj-info and switched to ```mp3agic```. Sorry for that, good luck and success :+1:

**Comment by caprica** [comment]
For the record, changing the above mentioned string to "MediaInfo" for Windows platforms does in fact work.

See 484d8d9c4cca6c0544e6e6ea9c7dab4d3b058fe7.

If it still doesn't work, probably there is a mismatch between JVM and native library CPU architectures (i.e. you must have 64-bit JVM with 64-bit native libraries, or 32-bit JVM with 32-bit native libraries).

**Comment by anshul90** [comment]
I have updated mediaIndo.dll file of 64-bit into my system as well. But still I'm facing below mentioned error

`Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'libmediainfo': JNA native support (win32-amd64/libmediainfo.dll) not found in resource path (C:\Users\anshul.c.tyagi\Downloads\RandomResearch\RandomResearch\target\classes;C:\Users\anshul.c.tyagi\.m2\repository\uk\co\caprica\vlcj-info\1.0.0\vlcj-info-1.0.0.jar;C:\Users\anshul.c.tyagi\.m2\repository\net\java\dev\jna\jna\3.5.2\jna-3.5.2.jar;C:\Users\anshul.c.tyagi\Downloads\eclipse\configuration\org.eclipse.osgi\412\0\.cp\lib\javaagent-shaded.jar)
`
